### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by JimmyMcBride** [Lambda-School-Labs/designhub-fe#261]
- [ ] Accurate project links Provide links to the staging server, production server, GitHub repositories, Trello/Notion board, and any additional services (continuous integration, analytics, exception monitoring, etc.) at the top of your PVD
- [ ] Clear tech stack summary Write a one-sentence summary at top of your PVD on the technical stack with the platform(s).
- [ ] Accurate release canvases Add 'complete' to the title of feature canvases you finished, and 'next step' to future ones. Inside finished feature canvases, the "solutions" should list what was actually released, not merely what was planned to be released at the start.
- [ ] Known defects Document known defects or bugs in a single column in Trello/Notion.
- [ ] Open questions Document research/discovery/stakeholder/feasibility/usability questions the next team should address during their discovery period.
- [ ] Contact info Team members name, roles, and contact info in the README of your codebase and/ or in the PVD.
- [ ] Credentials All your credentials (analytic tools, continuous integration, exception monitoring, staging, production, etc.) should be collected by your Team Lead and sent via Slack DM 
 to your Engineering Manager.
- [ ] TL Meeting For build-on's, meet with the new TL and document all current bugs and places for improvement.
- [ ] Prune Your Branches You should delete any branches in your repository that does not contain active work that will be picked up by the next Labs team. Ideally, you will end up with only your master branch and maybe one or two feature branches.
